In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
# sentenses
sent = [
    'the glass of milk', 
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your life is good'
] 

In [5]:
## define the vocabulary size
voc_size = 10000
## one hot represnetaion
one_hot_rep = [one_hot(word, voc_size) for word in sent]
print(one_hot_rep)

[[8293, 2287, 7630, 5048], [8293, 2287, 7630, 7899], [8293, 5046, 7630, 1642], [3474, 4949, 7478, 399, 7536], [3474, 4949, 7478, 399, 4598], [6215, 8293, 2630, 7630, 9111], [559, 3903, 4076, 399]]


In [9]:
# word embedding representaion 

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences  ## use this to make all the sentences of same size
from tensorflow.keras.models import Sequential

import numpy as np

In [10]:
# make all the vectores of same length
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8293 2287 7630 5048]
 [   0    0    0    0 8293 2287 7630 7899]
 [   0    0    0    0 8293 5046 7630 1642]
 [   0    0    0 3474 4949 7478  399 7536]
 [   0    0    0 3474 4949 7478  399 4598]
 [   0    0    0 6215 8293 2630 7630 9111]
 [   0    0    0    0  559 3903 4076  399]]


In [11]:
# Feature representaion for embedding
dimentions = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size,dimentions,input_length=sent_length))
model.compile('adam', 'mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 28ms/step


array([[ 0.04775394,  0.04996267,  0.03009004,  0.04801757,  0.02375648,
        -0.0056633 , -0.04129354,  0.00676201, -0.0483559 , -0.02109338],
       [ 0.04775394,  0.04996267,  0.03009004,  0.04801757,  0.02375648,
        -0.0056633 , -0.04129354,  0.00676201, -0.0483559 , -0.02109338],
       [ 0.04775394,  0.04996267,  0.03009004,  0.04801757,  0.02375648,
        -0.0056633 , -0.04129354,  0.00676201, -0.0483559 , -0.02109338],
       [ 0.04775394,  0.04996267,  0.03009004,  0.04801757,  0.02375648,
        -0.0056633 , -0.04129354,  0.00676201, -0.0483559 , -0.02109338],
       [-0.02799383, -0.02752397, -0.02278023,  0.04753963,  0.03081625,
         0.01667297,  0.02520067, -0.01417093, -0.04480617, -0.03034999],
       [-0.03264043,  0.0490538 ,  0.04198286, -0.01843464, -0.01178256,
        -0.0354221 , -0.0459585 , -0.0215916 , -0.01090582,  0.02870822],
       [-0.01824436,  0.01764807, -0.04271453, -0.04580253,  0.03635224,
         0.02294521,  0.0260894 ,  0.00692428